config/routes.rb
Hubzubub::Application.routes.draw do
  resources :search_sets


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :persons do
    resources :activities
  end

  resources :websites do
    resources :searches do
      resources :runs, controller: :search_runs
    end
		resources :params, controller: :website_params
  end
end

app/models/search_set.rb
class SearchSet
  include Mongoid::Document
  field :title, type: String
  field :description, type: String

  has_and_belongs_to_many :searches
end

app/controllers/search_sets_controller.rb
class SearchSetsController < ApplicationController
  # GET /search_sets
  # GET /search_sets.json
  def index
    @search_sets = SearchSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @search_sets }
    end
  end

  # GET /search_sets/1
  # GET /search_sets/1.json
  def show
    @search_set = SearchSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search_set }
    end
  end

  # GET /search_sets/new
  # GET /search_sets/new.json
  def new
    @search_set = SearchSet.new
    @searches = Search.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search_set }
    end
  end

  # GET /search_sets/1/edit
  def edit
    @search_set = SearchSet.find(params[:id])
    @searches = Search.all
  end

  # POST /search_sets
  # POST /search_sets.json
  def create
    @search_set = SearchSet.new(params[:search_set].slice(:title, :description))

    searches = params[:search_set][:searches].select(&:present?).collect { |search_id| Search.find(search_id)}
    @search_set.searches << searches

    respond_to do |format|
      if @search_set.save
        format.html { redirect_to @search_set, notice: 'Search set was successfully created.' }
        format.json { render json: @search_set, status: :created, location: @search_set }
      else
        format.html { render action: "new" }
        format.json { render json: @search_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /search_sets/1
  # PUT /search_sets/1.json
  def update
    @search_set = SearchSet.find(params[:id])

    respond_to do |format|
      if @search_set.update_attributes(params[:search_set])
        format.html { redirect_to @search_set, notice: 'Search set was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_sets/1
  # DELETE /search_sets/1.json
  def destroy
    @search_set = SearchSet.find(params[:id])
    @search_set.destroy

    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/search_sets_helper.rb
module SearchSetsHelper
end

app/views/search_sets/_form.html.haml
= form_for @search_set do |f|
  - if @search_set.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search_set.errors.count, "error")} prohibited this search_set from being saved:"
      %ul
        - @search_set.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label 'Searches'
    = f.collection_select :searches, @searches, :id, :long_description, {}, {multiple: true, name: 'search_set[searches][]'}
  .actions
    = f.submit 'Save'

app/views/search_sets/edit.html.haml
%h1 Editing search_set

= render 'form'

= link_to 'Show', @search_set
\|
= link_to 'Back', search_sets_path

app/views/search_sets/index.html.haml
%h1 Listing search_sets

%table
  %tr
    %th Title
    %th Description
    %th
    %th
    %th

  - @search_sets.each do |search_set|
    %tr
      %td= search_set.title
      %td= search_set.description
      %td= link_to 'Show', search_set
      %td= link_to 'Edit', edit_search_set_path(search_set)
      %td= link_to 'Destroy', search_set, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Search set', new_search_set_path

app/views/search_sets/new.html.haml
%h1 New search set

= render 'form'

= link_to 'Back', search_sets_path

app/views/search_sets/show.html.haml
%p
  %b Title:
  = @search_set.title
%p
  %b Description:
  = @search_set.description
%p
  %b Searches
  %ul
    - @search_set.searches.each do |search|
      %li
        = link_to search.long_description, website_search_path(search.website, search)

= link_to 'Edit', edit_search_set_path(@search_set)
\|
= link_to 'Destroy', @search_set, :confirm => 'Are you sure?', :method => :delete
\|
= link_to 'Back', search_sets_path