config/routes.rb
Hubzubub::Application.routes.draw do
  resources :search_sets


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :persons do
    resources :activities
  end

  resources :websites do
    resources :searches do
      resources :runs, controller: :search_runs
    end
		resources :params, controller: :website_params
  end
end

app/models/website.rb
class Website < Entity
	field :base_url
  field :description
	field :query_string

	field :next_page_param
	field :next_page_increment

	has_many :searches

	validates_presence_of :base_url #todo: validate format of base_url
	before_create :set_defaults
	
	embeds_many :website_params
  
  def site_description
    description || base_url
  end
  
	def create_search(search_term, format=nil)
		s = Search.new(website: self, url: search_url(search_term))
		unless format.nil?
			s.format = format
		end
		
		#s.result = s.run_search
		s
	end

	def search_url(search_terms="")
		if !website_params.blank? && website_params.collect(&:field_name).include?('search_url_format')
			#todo: user-specified params will allow custom search. still to be determined how best to do this
		else
			#this is google's format, each site will have its own
			"#{base_url}/#{query_string}#{search_terms.split.join("+")}"
		end
	end

	def store_search(search_term)
		search = create_search(search_term)
		searches << search
	end

	def set_defaults
		unless base_url.starts_with?('http://') or base_url.starts_with?('https://')
			self.base_url = 'http://'+ self.base_url
		end
	end
	
	def self.url_pattern?(string)
		string =~ /^[a-zA-Z0-9\-\.]+\.(com|org|net|mil|edu|COM|ORG|NET|MIL|EDU)$/
	end
	
	def self.existing?(url)
		Website.where(url: "http://#{url}").or(url: "https://#{url}").first
	end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  
  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all

    respond_to do |format|
      #format.html # index.html.erb
	  redirect_to root_path
      format.json { render json: @websites }
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website = Website.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
    @website = Website.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website }
    end
  end

  # GET /websites/1/edit
  def edit
    @website = Website.find(params[:id])
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new
		populate_attributes(@website, params[:website])
    
    respond_to do |format|
      if @website.save
        format.html { redirect_to  @website, notice: 'Website was successfully created.' }
        format.json { render json: @website, status: :created, location: @website }
      else
        format.html { render action: "new" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end
	
	def multi_create
		if params[:add_websites]
			website_urls = params[:add_websites]
		end
		
		successful_creates = Array.new
		fails = Array.new
		website_urls.each do |u|
			w = Website.new(base_url: u)
			if w.save
				successful_creates << w.base_url
			else
				fails << w.base_url
			end
		end
		
		respond_to do |format|
			format.html { redirect_to root_path, notice: "Websites successfully created: #{successful_creates.join(",")}, fails: #{fails.join(",")}" }
			format.json { render json: @website, status: :created, location: @website }
    end
	end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website = Website.find(params[:id])
	populate_attributes(@website, params[:website])
    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website = Website.find(params[:id])
    @website.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
  
  private
  def populate_attributes(instance, params)
	if params && params.is_a?(Hash) && !params.keys.empty?
	  params.keys.each do |field|
	    instance.send("#{field}=", params[field])
	  end
	end
	
	instance
  end

end

app/views/websites/_form.haml
= form_for @website do |f|
  -if @website.errors.any?
    #error_explanation
      %h2= "#{pluralize(@website.errors.count, "error")} prohibited this website from being saved:"
      %ul
        - @website.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Base Url"
    = f.text_field :base_url
  .field
    = f.label "Description"
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/websites/edit.haml
%h1 Editing person

= render 'form'

= link_to 'Show', @website
\|
= link_to 'Home', root_path

app/views/websites/new.haml
%h1 New website

= render 'form'

= link_to 'Home', root_path(@user)

app/views/websites/show.haml
%p
  = @website.base_url
  - if @website.description
    = "(#{@website.description})"

- unless @website.searches.blank?
  %p
    Searches on
    = @website.base_url

  %ul
    - @website.searches.each do |s|
      %li
        - if s.description
          = s.description
        = link_to s.url, website_search_path(@website, s)

- if @website.query_string.present?
  %p
    Query string:
    = @website.query_string

- if @website.next_page_param.present?
  %p
    Next page param:
    = @website.next_page_param

- if @website.next_page_increment.present?
  %p
    Next page increment:
    = @website.next_page_increment

%p
= link_to 'Home', root_path
\|
= link_to 'Edit', edit_website_path(@website)
\|
= link_to "New Search", new_website_search_path(@website)
\|
= link_to 'Destroy', @website, :confirm => 'Are you sure?', :method => :delete