config/routes.rb
Hubzubub::Application.routes.draw do
  resources :search_sets


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :persons do
    resources :activities
  end

  resources :websites do
    resources :searches do
      resources :runs, controller: :search_runs
    end
		resources :params, controller: :website_params
  end
end

app/models/website_param.rb
class WebsiteParam
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name
  field :description
  field :field_name
  field :field_value
  
  embedded_in :website
	
	validates_presence_of :name, :field_name
  
  scope :search_params, where(field_name: /^[search_param]/)
  scope :parse_params, where(field_name: /^[parse_param]/)
end

app/controllers/website_params_controller.rb
class WebsiteParamsController < ApplicationController
  before_filter :find_website
	
  # GET /websites
  # GET /websites.json
  def index
    @website_params = @website.website_params

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @website_params }
    end
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
    @website_param = @website.website_params.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @website_param }
    end
  end

  # GET /websites/new
  # GET /websites/new.json
  def new
    @website_param = @website.website_params.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @website_param }
    end
  end

  # GET /websites/1/edit
  def edit
    @website_param = @website.website_params.find(params[:id])
  end

  # POST /websites
  # POST /websites.json
  def create
    @website_param = @website.website_params.new
		
		populate_attributes(@website_param, params[:website_param])
    
    respond_to do |format|
      if @website_param.save
        format.html { redirect_to website_params_path(@website), notice: 'Website params was successfully created.' }
        format.json { render json: @website_param, status: :created, location: @website_param }
      else
        format.html { render action: "new" }
        format.json { render json: @website_param.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /websites/1
  # PUT /websites/1.json
  def update
    @website_param = @website.website_params.find(params[:id])
		populate_attributes(@website_param, params[:website])
    respond_to do |format|
      if @website_param.save
        format.html { redirect_to website_params_path(@website), notice: 'Website params was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @website_param.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website_param = @website.website_params.find(params[:id])
    @website_param.destroy

    respond_to do |format|
      format.html { redirect_to website_params_path(@website) }
      format.json { head :no_content }
    end
  end
  
  private
  def populate_attributes(instance, params)
		if params && params.is_a?(Hash) && !params.keys.empty?
			params.keys.each do |field|
				instance.send("#{field}=", params[field])
			end
		end
		
		instance
  end
	
	def find_website
    @website = Website.where(id: params[:website_id]).first
  end

end

app/views/website_params/_form.haml
= form_for @website_param, :url=>path_var do |f|
  -if @website_param.errors.any?
    #error_explanation
      %h2= "#{pluralize(@website_param.errors.count, "error")} prohibited this website_param from being saved:"
      %ul
        - @website_param.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Name:"
    = f.text_field :name
  .field
    = f.label "Description:"
    = f.text_field :description
  .field
    = f.label "Field Name:"
    = f.text_field :field_name
  .field
    = f.label "Value:"
    = f.text_field :field_value
  .actions
    = f.submit 'Save'

app/views/website_params/edit.haml
%h1 Editing website_param

= render :partial=>'form', :locals=>{:path_var=>website_param_path(@website, @website_param)}

= link_to 'Show', @website_param
\|
= link_to 'Home', root_path

app/views/website_params/index.haml
%p
	Website Params on
	= @website.base_url

- unless @website.website_params.blank?
	%ul
		- @website.website_params.each do |s|
			%li
				param:
				= link_to s.field_name, website_param_path(@website, s)
				- unless s.description.blank?
					, description:
					= s.description
				, value:
				= s.field_value

%p
	= link_to "New Param", new_website_param_path(@website)

app/views/website_params/new.haml
%h1 New website param

= render :partial=>'form', :locals=>{:path_var=>website_params_path(@website, @website_param)}

= link_to 'Back', website_params_path(@website)

app/views/website_params/show.haml
%p
	Name:
	= @website_param.name
%p
	Description
	= @website_param.description
%p
	Field name:
	= @website_param.field_name
%p
	Value:
	= @website_param.field_value

%p
= link_to 'Home', root_path
\|
= link_to 'Edit', edit_website_param_path(@website, @website_param)
\|
= link_to 'Destroy', website_param_path(@website, @website_param), :confirm => 'Are you sure?', :method => :delete