config/routes.rb
Hubzubub::Application.routes.draw do
  resources :search_sets


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  resources :persons do
    resources :activities
  end

  resources :websites do
    resources :searches do
      resources :runs, controller: :search_runs
    end
		resources :params, controller: :website_params
  end
end

app/models/search.rb
require 'nokogiri'

class Search
  include Mongoid::Document
  field :url
  field :description
	field :search_type
  field :format
  field :selector
  field :terms, type: Array

  belongs_to :website
  has_and_belongs_to_many :search_sets

  has_many :search_runs

  def run_search
  	return nil if url.nil?

  	case format
  	when 'json'
  		json_search
  	else
  		html_search.body #figure this out...
  	end
  end

  def html_search
  	Page.get url
  end

  def json_search
  	JSON.parse(open(url))
  end

  def long_description
    "#{website.site_description} - #{self.description}"
  end

	def scan(terms=[])

		results_array = Array.new

		doc = Nokogiri::HTML(run_search)

    doc.css(self.selector).each do |node|
      # binding.pry

      if self.terms.present?
        self.terms.split(' ').each do |term|
          if node.text.scan(term).present?
            results_array << {text: node.text, url: node['href']}
            break
          end
        end
      else
        results_array << {text: node.text, url: node['href']}
      end

    end

    results_array
	end

	def self.search_types
		['search_site', 'parse_page']
	end

end

class HtmlParserIncluded < HTTParty::Parser
  SupportedFormats.merge!('text/html' => :html)

  def html
    Nokogiri::HTML(body)
  end
end

class Page
  include HTTParty
  parser HtmlParserIncluded
end

class JSONPage
  include HTTParty
  parser :json
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  before_filter :find_website

  # GET /searchs
  # GET /searchs.json
  def index
    @searches = @website.searches.all

    respond_to do |format|
      format.html #index.html.erb
      format.json { render json: @searches }
    end
  end

  # GET /searchs/1
  # GET /searchs/1.json
  def show
    @search = Search.find(params[:id])
    @search_run = SearchRun.new

		# if params[:search_result]

  #     search_terms =
  #       if params[:search_result][:use_description_terms] == '1'
  #         @search.description.split(' ')
  #       else
  #         []
  #       end

  #     search_results = @search.scan(params[:search_result][:selector], search_terms)

  #     search_run = SearchRun.new(search_url: @website.search_url, selector: params[:search_result][:selector])
  #     @search.search_runs << search_run

  #     search_results.each do |result|
  #       url = result[:url]

  #       url = @website.base_url + result[:url] if result[:url].start_with?('/')

  #       search_run.search_run_results << SearchRunResult.new(text: result[:text], url: url)
  #     end
		# end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searchs/new
  # GET /searchs/new.json
  def new
    @search = Search.new
		@search_types = Search.search_types

    @search.url = @website.search_url

    @site_search_params = @website.website_params.search_params
    @site_parse_params = @website.website_params.parse_params

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @search }
    end
  end

  # GET /searchs/1/edit
  def edit
    @search = Search.find(params[:id])
		@search_types = Search.search_types
    @site_search_params = @website.website_params.search_params
    @site_parse_params = @website.website_params.parse_params

    if params[:search_terms]
      @search.url = @website.search_url(params[:search_terms])
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /searchs
  # POST /searchs.json
  def create
    @search = @website.searches.new params[:search]

		@search.url = @website.search_url(params[:search_terms]) if params[:search_terms]

    @search.terms = @search.description.split(' ') if params[:use_description_terms]

    respond_to do |format|
      if @search.save

        format.html { redirect_to  website_search_url(@website, @search), notice: 'Search was successfully created.' }
        format.json { render json: @search, status: :created, location: @search }
      else
        format.html { render action: "new" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /searchs/1
  # PUT /searchs/1.json
  def update
    @search = Search.find(params[:id])
    #populate_attributes(@search, params[:search])
    @search.update_attributes(params[:search])

    if params[:search_terms]
      @search.url = @website.search_url(params[:search_terms])
    end

    respond_to do |format|

      if @search.save
        format.html { redirect_to [@website, @search], notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searchs/1
  # DELETE /searchs/1.json
  def destroy
    @search = Search.find(params[:id])
    @search.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
  def populate_attributes(instance, params)
  	if params && params.is_a?(Hash) && !params.keys.empty?
  	  params.keys.each do |field|
        unless params[field].blank? || instance.respond_to?(field.to_s) == false
          instance.send("#{field}=", params[field])
        end
  	  end
  	end

	 instance
  end

  def find_website
    @website = Website.where(id: params[:website_id]).first
  end

end

app/views/searches/_form.haml
.search_url
  = render 'search_url'

app/views/searches/_found_websites.haml
- if !@found_websites.blank?
  = form_for(:found_websites, :url=>multi_create_website_path(@website)) do |f|
    %p
      New websites found. Select to add
      - @found_websites.each do |f|
        %br
          = check_box_tag("add_websites[]", f, true)
          = f
      = f.submit "Add"
- if !@person_results.blank?
  %p
    Created activities
    %ul
      - @person_results.each do |a|
        %li
          = "#{a.person.name}: #{a.url}"

app/views/searches/_search_terms.haml
= form_for(@search, :url=>edit_website_search_url(@website, @search), :html=>{:method=>:get, :id=>'search'}, :remote=>true) do |f|
  = f.label "Search terms (separated by space)"
  #search_field
    = text_field_tag :search_terms, nil, :class=>"span5"
  .field
    = f.label "Add site-specific params"

    - if @website.next_page_param && @website.next_page_increment
      %p
        %button#next_page Add

        %span#next_page_param
          = "#{@website.next_page_param}=#{@website.next_page_increment}"

    - @site_search_params.each do |p|
      %button Add
      = p.field_name
      \=
      = p.field_value
    %br

:javascript
  $(function(){

    $('#search_field').keyup(function() {
      $("form#search").submit();
    })

    $('button#next_page').click(function() {

    })

  });

app/views/searches/_search_url.haml
= form_for [@website, @search] do |f|
  -if @search.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search.errors.count, "error")} prohibited this search from being saved:"
      %ul
        - @search.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label "Website:"
    = @website.base_url
  .field
    = f.label "Description:"
    = f.text_field :description
  .field
    = f.label "Search url: "
    = f.text_field :url, :class=>"span5"
  .field
    = f.label 'CSS Selector'
    = f.text_field :selector

  - if params[:action] == 'new'
    .field
      = check_box_tag(:use_description_terms)
      Search for description in results
  - elsif params[:action] == 'edit'
    = f.label 'Search Terms'
    = f.text_field :terms
  %br
  = f.submit 'Save'

app/views/searches/edit.haml
%h1 Editing search

= render 'form'

= link_to 'Show', [@website, @search]
\|
= link_to 'Home', root_path

app/views/searches/edit.js.erb
$('.search_url').html("<%=j render 'search_url' %>");

app/views/searches/index.haml
%p
  Searches on
  = @website.base_url

- unless @website.searches.blank?
  %ul
    - @website.searches.each do |s|
      %li
        - if s.description
          = s.description
        = link_to s.url, website_search_path(@website, s)

= link_to "Website", website_path(@website)
\|
= link_to "New Search", new_website_search_path(@website)

app/views/searches/new.haml
%h1 New search

= render 'form'

= link_to 'Back', website_path(@website)

app/views/searches/show.haml
%p
  %b Search Url:
  = @search.url
%p
  %b Description:
  = @search.description

- unless @search.search_type.blank?
  %b Type:
  = @search.search_type.humanize

%p
  %b CSS Selector:
  = @search.selector
%p
  %b Search Terms:
  = @search.terms

= form_tag(website_search_runs_path(@website, @search, @search_run), method: :post) do |f|
  = submit_tag "Run a scan"

- if @search.search_runs.present?
  Searches Run:

%ul
  - @search.search_runs.each do |run|
    %li
      = link_to run.created_at, website_search_run_path(@website, @search, run)
      Selector:
      = "'#{@search.selector}'"
      = "#{run.search_run_results.count} results found."

%p
= link_to 'Searches', website_searches_path(@website)
\|
= link_to 'Edit search params', edit_website_search_path(@website, @search)
\|
= link_to 'Destroy', [@website, @search], :confirm => 'Are you sure?', :method => :delete